max_width = 100
overflow_delimited_expr = true
use_small_heuristics = "Max"
fn_single_line = true
merge_imports = true
reorder_impl_items = true
blank_lines_upper_bound = 3
comment_width = 100
wrap_comments = true